dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
after_script:
  - npx semantic-release
branches:
  only:
    - master
