dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script:
        - npx semantic-release
branches:
  only:
    - master
